### ISSUE TITLE
JLCPCB Unavailable Part/Suggestions

### ISSUE THREAD

**Issue by pwnept** [TobleMiner/ESP32-Devkit-Type-C#4]
- LQH32CN4R7M23L Inductor is on "inventory shortage" and is currently unavailable for SMT assembly.
- The MP2359 is just listed as No part selected.
- I found some USB 2.0 type C connectors that can probably be used:
[](https://lcsc.com/product-detail/USB-Connectors_SHOU-HAN-TYPE-C-DT6P-DIP_C456010.html)
[](https://lcsc.com/product-detail/USB-Connectors_Jing-Extension-of-the-Electronic-Co-918-418K2022Y40001_C399924.html)
[](https://lcsc.com/product-detail/USB-Connectors_Shenzhen-Kinghelm-Elec-KH-TYPE-C-6P_C709355.html)
[](https://lcsc.com/product-detail/USB-Connectors_SHOU-HAN-TYPE-C-6P-073_C668623.html)
- AFAIK the CH340G can be replaced with the pin-compatible recommended-part-class CH340C, then the external oscillator crystal and capacitors  can be removed because the CH340C has them built in.
-The switches showed up as assembly-ready.

![screencapture-cart-jlcpcb-smtQuote-2021-04-24-20_09_58](https://user-images.githubusercontent.com/34002935/115959961-150fad80-a539-11eb-8c56-ac0f31ff81c4.png)

I have no idea if these are good suggestions or not as I have zero experience in PCB design.
Thank you for making this project!

**Comment by moucha19** [comment]
For anyone interested in solution to mentioned issues, I made a fork with slight changes that could help. You can find it [here](https://github.com/moucha19/ESP32-Devkit-Type-C).

**Comment by rrooggiieerr** [comment]
@moucha19 Thanks for the updated design. However the MP2259 seems to be difficult to source. Apparently the MP2331H is the successor of the MP2359.
